# -*- coding: utf-8 -*-
"""08th june.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_t4G-NzcBQ0rgJmuFtHQPPLqRtEfXxIK
"""

for i in range(1,6):
  print(i)

#iterating over a list
fruits=["apple","banana","mango"]
for a in fruits:
  print(a)

for i in range(10):
  print(i)

#nested loop(akta loop er vitor ar akta loop)
for i in range(1,6):
    for j in range(1,4):
        print("i=",i,"j=",j,)

numbers=[1,2,3,4,5]
total=0
for a in numbers:
  #total+=a        (same same but difflant)
  total=a+total
  print("Total sum: ",total,)

numbers=[20,30,40,50,60,70]
max_num=numbers[0]
for a in numbers:
  if a>max_num:
    max_num=a
print("Maximum Number: ",max_num, )

a=10
while a>=1:
  #a-=1
  print(a)
  a-=1

b="python"
for a in b:
  print(a)

for i in range(1,6):
  for j in range(1,i+1):
    print(j,end="")
  print()

#function defination
def saiful():
  print("Hello world")
saiful()

def greet(name):
  print("Helo",name,)
greet("Saiful")

monday=[4,5,1,3]
tuesday=[1,2,3,4]
wednesday=[1,2,3,4]

def saiful():
  sum=0
  for a in monday:
    sum=sum+a

  average=sum/4
  print(monday)
  print(tuesday)
  print(wednesday)
  print(average)
saiful()

def greet(name,age):
  print("Helo",name,"your age is ",age,)
greet("Saiful",25),30

def add(a,b):
  return a+b
result=add(10,20)
print(result)

#lambda function
add_lambda=lambda a,b:a+b
result=add_lambda(10,20)
print(result)

print(add(10,20))
print(add_lambda(10,20))

#from functools import reduce
#example with map()
numbers=[1,2,3,4,5]
squared=list(map(lambda x:x**2,numbers))
print(squared)

#example with filter()
evens = list(filter(lambda x: x % 2 == 0, numbers))
squared=list(map(lambda x:x**2,numbers))
print(evens,squared)